### ISSUE TITLE
Crawling on trees

### ISSUE THREAD

**Issue by NobodyYouKnow01** [Retro64Mod/Retro64Mod.github.io#16]
Expected behavior: In certain gaps, Mario looks short enough to crawl through.
Actual Behavior: Not only does Mario not fit through the gap, he proceeds to climb the wall he's moving towards. This is most notable with trees.

https://imgur.com/a/3pGkCnv

**Comment by NobodyYouKnow01** [comment]
I think I may have duplicated issue #8 ... I'll let you close it if so

**Comment by Mario9501** [comment]
The reason this happens is because Mario's hitbox will always have a 160 unit buffer from a ceiling (even if you crawl.)  [Ceiling hitboxes will always extend 160 units downward I would recommend watching this video to have a better understanding of how ceilings work.] https://youtu.be/f1kbABTyeo8 go to 10:40 for information about how they work.
