### ISSUE TITLE
Mario can regenerate air from 1px air pocket in cave

### ISSUE THREAD

**Issue by PinPanPaint** [Retro64Mod/Retro64Mod.github.io#49]
![2022-04-04_18 43 02](https://user-images.githubusercontent.com/70254789/161662870-c5776c65-7826-471a-99aa-19c0299ec109.png)

Self explanatory. These are usually at the tops of water caverns, normally u cannot regen air.
However mario can!

**Comment by Lilkaosr** [comment]
I know that no one asked but Ima have my input on this
I think its due to the fact that the mod counts a water source block as not a full block, this can be seen when you walk in a one block deep pool of water. I think that since the water isn't entirely full. This allows the mario 64 game in interperet this "small in terms of minecraft but still large in terms of mario 64" gap to allow mario to breath.

**Comment by dylanpdx** [comment]
Fixed in latest version
