### ISSUE TITLE
Optifine breaks block collison 

### ISSUE THREAD

**Issue by MrStoic** [Retro64Mod/Retro64Mod.github.io#64]
If you have optifine installed it breaks the Collison system and makes every block except air behave like a full one.

![bug](https://user-images.githubusercontent.com/85310815/162860909-871cb857-7279-4d1d-903b-4e1d75cc5106.gif)
(my friend has optifine on and i dont)

**Comment by dylanpdx** [comment]
The mod currently is not compatible with shaders or optifine, and causes odd issues like this.
If you absolutely must use optifine, shaders need to be fully disabled (not set to internal) for collisions to work properly.
This issue is partly my fault due to the hacky way i'm getting collision data, but I can't really implement a fix until I have time to take a look at it
